### ISSUE TITLE
Add Mexican names to localised data list

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-mexico#14]
take names in
https://docs.google.com/spreadsheets/d/1ttpLn-rPRBYXScWuW_vPwTcsjT3R2HJ1R5v5dYWx2F8/edit#gid=0
and update file in 
https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=377173726

**Comment by edmoss345** [comment]
@fagiothree believe this is done and can be closed
