### ISSUE TITLE
Set up goal API 

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-mexico#26]
Files in https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=733606289

**Comment by fagiothree** [comment]
Need to update data models to include column names

**Comment by istride** [comment]
LTP Activities:

https://docs.google.com/spreadsheets/d/1DVtLMR0gm3tzzgaA0A_1b9iQi8758WJFoGET3WWUCm4/edit?usp=sharing

>there are 2 sheets in this case and we would need to concatenate them

**Comment by istride** [comment]
Goals API deployed for Mexico. The URL to use is http://mx.goals.api:8080
