### ISSUE TITLE
Set up api for completion certificates

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-mexico#28]
For Mexico and future deployments, instead of having a single certificate delivered at the end, they'll receive one certificate after each course. This implies that we have essentially 2 text spaces to fill:
1 for the user's first and last name (Apple Chancery works great here)
1 for the name of the course (since they receive 1 certificate at the end of each course). Here, our designer has suggested Noto Sans for scalability. Is this feasible for your requirements?

https://fonts.google.com/noto

**Comment by istride** [comment]
The certificate API that was recently deployed for ParentText China is slightly different from Malaysia, and that could help us here. The China API requires two pieces of information to create a certificate:

- name of recipient
- name of template

This means that we could have many certificate templates (one for each course), so there would be no need to change the API to support 2 areas of customisation.

We should use the same version of the API for Mexico, and eventually upgrade the one that is currently being used for Malaysia.

**Comment by fagiothree** [comment]
I think Laurie would prefer to have a single image (actually 2, one for Spanish and one for English) for scalability, so partners don't need to produce new images as they add new courses. What could be a compromise?

**Comment by istride** [comment]
Just waiting for templates.

**Comment by istride** [comment]
Deployed Certificator for Mexico with default template.

**Comment by istride** [comment]
Expecting certificate templates on Tuesday 6 February.

**Comment by istride** [comment]
Templates are available in the API.
