### ISSUE TITLE
Add variable for child gender to replace the world "child"

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#3]
Spanish does not have a language equivalent to "your child" or "a child" or "the child." Where the child's name (i.e. Your Child) is not appropriate, we need a variable to populate boy or girl (niño y niña). The variables can appear as {child} and {the_child}. Based on the gender of the child entered during onboarding, gender-specific content appears. 

For example: 

Your {child} is always learning. 
will be translated as 
Tu {child} siempre esta aprendiendo.
and appear to the parent of a boy as:
Tu niño siempre esta aprendiendo.

**Comment by esmeetewinkel** [comment]
I guess you would want to capture also the article or pronoun in the variable {your_child}, since that might change depending on the (gender of the) noun. E.g. french "my child" = "mon enfant"

**Comment by lauriemarkle** [comment]
In Spanish it's tu niño o tu niña. The same.

**Comment by fagiothree** [comment]
The proposed strategy is described here: https://docs.google.com/document/d/1Po8t04m5xEx-ZzbM8vh5j3af3-hpygpHoCkuxWtNEgg/edit?usp=sharing
after messages have been authored using {child} ad placeholder, we need to define post-translation edits in https://docs.google.com/spreadsheets/d/1BuVd7L66tJ8KNW0vZQbujyBagz_coOLQH9kEGQYsFWQ/edit#gid=121447424
see 
![image](https://github.com/IDEMSInternational/parenttext-mexico/assets/32491856/95df905f-0e6f-4694-a59e-afed99ed565d)
