### ISSUE TITLE
Change "Your Research ID is..."

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#64]
When the user begins ParentText, they first receive the message "Your Research ID is..." followed by a UID. This language does not seem to appear in the editable data lists. Please revise it to "Your user ID is..."

**Comment by lauriemarkle** [comment]
@fagiothree FYI this should be updated, translated, and tested before pilot begins.

**Comment by fagiothree** [comment]
@lauriemarkle  the message is here https://docs.google.com/spreadsheets/d/1wKAk5fom5fwjvrBMonATo1aU2mVjQfJjbhcajxsB5Xg/edit#gid=1144099476
I edited it accordingly
