### ISSUE TITLE
Turn off UID Share for Facilitator Triggers

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#65]
Users who enrol via the trigger "FACENTRENAR" should not receive the initial message "Your User ID is..." followed by UID. This is confusing for facilitators who have a separate ID generated from the facilitator app. 

One possible solution is assigning a variable to users who enter this trigger v other enrolment triggers. Then assigning the research ID flow only to users with selected variables. --> This should be a global feature.

**Comment by lauriemarkle** [comment]
@fagiothree this is due prior to the pilot.

**Comment by fagiothree** [comment]
created a wrapper for the flow launched by FACENTRENAR (safeguarding_start_programme) defined in https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit?gid=2020906605#gid=2020906605
so that language is set to spanish and ID is skipped
