### ISSUE TITLE
Add possibility to continue progress from MENU and HELP

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#67]
Parents are often getting stuck after completing MENU or HELP flows and are not getting notifications the following day. To allow users to continue their progress after engaging with the MENU or HELP flows, we will add options in those flows to do so.

NOTE: It is possible that a user then uses this trigger to complete more than one module in a day, but this is an edge case. The opportunity to ease user engagement and avoid drop out is most critical. 

This feature should be built, translated, and tested prior to the pilot.

**Comment by fagiothree** [comment]
@lauriemarkle all the menu messages are editable and in this data list https://docs.google.com/spreadsheets/d/1lwmMa18SM7bUR-og__daYgDNlEfwnj-KtLjC7Cw-EHo/edit#gid=0
