### ISSUE TITLE
Localised chatbot name

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#68]
Where ParentText is replaced with "Crianza con Conciencia+" for users who register in Chihuahua State, a different programme name will be used. 

Because users do not select their state prior to giving consent, facilitators in Chihuahua will need to be provided enrolment triggers that are unique to their state and allow for users to receive the updated programme name. 

To facilitate this change we will need _both_ added trigger rows with a separate user group, the ability to differentiate programme name based on user group, and a cell to indicate the revised programme name in the data list structure.

In post-translation edits, where the localised name of ParentText is listed, we need the name of the programme to be differentiated based on the enrollment trigger used by the caregiver. 

In Mexico, parents who enroll from Chihuahua state (using trigger AFECTIVA) will not receive Crianza Con Conciencia+ as their programme name, but will receive "Crianza Afectiva"

**Comment by lauriemarkle** [comment]
Due prior to pilot

**Comment by fagiothree** [comment]
The variable "prog_name" is set at registration with different values based on the trigger used
AFECTIVA --> Crianza Afectiva
other triggers --> Crianza Con Conciencia+
https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=1932032165
in post-translation edits, all occurrences of the programme name (which is first replaced in the English source text with "ParentText" to restore consistency, see #72)  are replaced with the expression
@(if(fields.prog_name, fields.prog_name,"Crianza con Conciencia+")) which will be replaced at run time with the actual value and takes into account the fact that users who enrolled prior to the pilot won't have a value stored in @fields.prog_name, so it will default to "Crianza Con Conciencia+"
https://docs.google.com/spreadsheets/d/1BuVd7L66tJ8KNW0vZQbujyBagz_coOLQH9kEGQYsFWQ/edit#gid=1767436012
