### ISSUE TITLE
Parent Gender Attribute to Differentiate Available Learning Goals (Courses)

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-mexico#69]
In Mexico, the IPV course is only appropriate for male caregivers. 
An attribute for parent_gender has been added to the goal_data sheet in [localised lists and data flows](https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=733606289). 

This feature is part of the pilot milestone, due Friday, June 3.

**Comment by fagiothree** [comment]
redefined set_up_prog_var flow so it uses the use_webhook_get_goals_list_parametrised template, where the filter expression for getting goal list can be specified as an argument:
'@fields.get_ipv_content' in relationship and '@fields.attachment_gender' in parent_gender

https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=1106330471
